Fjerne ansatt når vedkommende ikke lenger er koordinator
navikt/amt-tiltak pull request #337
Opened 2023-01-09 12:18 UTC by magnusev

2023-01-09 12:37 UTC, magnusev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fjerne ansatt når vedkommende ikke lenger er koordinator](https://trello.com/c/Gdx2szjr/523-fjerne-ansatt-n%C3%A5r-vedkommende-ikke-lenger-er-koordinator)

2023-01-10 11:36 UTC, AlexGaard requested changes

2023-01-10 11:36 UTC, AlexGaard commented on tilgangskontroll-tiltaksarrangor/src/main/kotlin/no/nav/amt/tiltak/tilgangskontroll_tiltaksarrangor/tilgang/jobs/ArrangorAnsattTilgangUpdater.kt
> +	}
Kunne vurdert å inline denne.

Mangler forresten sjekk på at sistoppdatert er eldre enn f.eks 7 dager før vi gjør neste oppdatering

2023-01-10 11:41 UTC, AlexGaard requested changes

2023-01-10 11:41 UTC, AlexGaard commented on arrangor/src/main/kotlin/no/nav/amt/tiltak/ansatt/ArrangorAnsattServiceImpl.kt
> +	}
Lurer kanskje på om det er bedre å bruke `setSistOppdatertForAnsatt(ansattId: UUID, sistOppdatert: LocalDateTime)` og `getAnsatteSistSynkronisertFra(eldreEnn: LocalDateTime, maksAntall: Int): List<ArrangorAnsatt>`.

Usikker på navnet `getAnsatteSistSynkronisertFra`

2023-01-11 07:25 UTC, magnusev commented on arrangor/src/main/kotlin/no/nav/amt/tiltak/ansatt/ArrangorAnsattServiceImpl.kt
> +	}
Veldig enig!

2023-01-11 10:47 UTC, AlexGaard approved these changes

2023-01-11 10:54 UTC, merged