Legger på feilhåndtering på pdl connector
navikt/amt-tiltak pull request #88
Opened 2022-01-18 14:34 UTC by izisfro

2022-01-18 14:41 UTC, AlexGaard requested changes

2022-01-18 14:41 UTC, AlexGaard commented on connectors/pdl/src/main/kotlin/no/nav/amt/tiltak/connectors/pdl/PdlConnectorImpl.kt
> +				throw RuntimeException("Error i respons fra pdl: $melding")
Hvis man kaster et exception i forEach, så vil den stoppe etter å ha kastet et exception på den første feilen.
Det er kanskje bedre å loope over å samle feilmeldingene og deretter kaste exception.

2022-01-18 15:26 UTC, izisfro commented on connectors/pdl/src/main/kotlin/no/nav/amt/tiltak/connectors/pdl/PdlConnectorImpl.kt
> +				throw RuntimeException("Error i respons fra pdl: $melding")
Haha, sant det!

2022-01-19 06:29 UTC, izisfro commented on connectors/pdl/src/main/kotlin/no/nav/amt/tiltak/connectors/pdl/PdlConnectorImpl.kt
> +				throw RuntimeException("Error i respons fra pdl: $melding")
Lurer litt på å bare bruke slf4j loggingen isteden, eller bryr vi oss om at de skal være gruppert?

2022-01-19 06:50 UTC, izisfro commented on connectors/pdl/src/main/kotlin/no/nav/amt/tiltak/connectors/pdl/PdlConnectorImpl.kt
> +				throw RuntimeException("Error i respons fra pdl: $melding")
Konkatinerte de jeg. Kan du ta en titt?

2022-01-19 07:51 UTC, AlexGaard approved these changes

2022-01-20 21:39 UTC, merged